vm/ieleClientUtils.ml
Corresponds to changes in runtimeverification/iele-semantics#105
=> rename "data" field for contract creation to contractCode

vm/ieleApi.ml, vm/ieleClientUtils.ml, vm/ieleVmTest.ml
Fixes an issue with negative integers passed to the solidity test harness.
=> fix of_hex for signed integers in ieleApi.ml

plugin/world.ml
=> refactor vm to use Unix.establish_server

vm/VM.ml
=> Constantinople

plugin-c/crypto.cpp
This adds the KRYTPO hooks for the LLVM backend.
=> crypto.cpp for llvm backend

plugin/world.ml, plugin/world.mli, vm/VM.ml, vm/ieleApi.ml, vm/ieleClientUtils.ml, vm/ieleVmTest.ml
looks like I forgot to get this merged before merging the iele gas model. @bmmoore can you please review?
=> iele gas model update

vm-c/vm.cpp, vm/VM.ml
In reference to: https://github.com/kframework/evm-semantics/pull/335
=> Updates to add <kevm> wrapper cell to EVM configuration

client-c/main.cpp
Add proper option parsing support for client.
=> Option parsing

client-c/main.cpp
=> Shutdownable flag to allow VM to shutdown

Jenkinsfile, plugin-c/crypto.cpp, vm-c/vm.cpp
Changes I needed to get the beacon chain stuff to build with the latest LLVM backend.
=> Update for LLVM backend interface changes.

vm-c/vm.cpp
=> fix warnings

client-c/json.cpp
Fixes runtimeverification/firefly#282
=> print configuration before aborting

client-c/json.cpp
fixes: https://github.com/runtimeverification/firefly/issues/299
=> Return error term on bad JSON

Dockerfile, Jenkinsfile, Makefile, client-c/HttpHandler.cpp, client-c/HttpHandler.h, client-c/HttpStats.h, client-c/main.cpp, client-c/readme.md
Fixes: runtimeverification/firefly#336
This pull request adds an http server which is able to communicate with external clients like Truffle.
It will receive a `json-rpc` message as a body of an `HTTP POST` request. The `HttpHandler` will take the `json-rpc` message and send it over an `AF_INET` socket to the K server. After the rpc message is processed, a response will be sent back to the client.
=> Web3: Add proxygen HTTP Server

client-c/json.cpp
fixes: runtimeverification/firefly#345
=> fix bug in write_json

client-c/main.cpp
Fixes: https://github.com/runtimeverification/firefly/issues/378
=> Close hanging socket

Makefile, plugin-c/blake2.cpp, plugin-c/blake2.h, plugin-c/crypto.cpp
Makes progress on https://github.com/runtimeverification/firefly/issues/265
[evm-semantics PR](https://github.com/kframework/evm-semantics/pull/618)
[Here's the reference implementation that was used](https://tools.ietf.org/html/rfc7693#appendix-C.2)
=> Blake2 compression function F

LICENSE
=> LICENSE: add license file

client-c/main.cpp
For https://github.com/runtimeverification/firefly/issues/480
`evm-semantics` PR: https://github.com/kframework/evm-semantics/pull/679
=> Add --dump flag to client

.gitmodules, Makefile, client-c/main.cpp
This reverts commit 1d4f18a463aa35b4f0cac8dbdca3adacf58305f9.
This update is causing updates from KEVM -> Firefly to fail, and we're not using it yet anyway.
=> Revert "Add websocket support (#88)"

Makefile, client-c/json.cpp, client-c/main.cpp
See kframework/evm-semantics#755
=> use pipes instead of a socket for communication with K

client-c/main.cpp
fixes: https://github.com/runtimeverification/firefly/issues/872
Sister PR: https://github.com/kframework/evm-semantics/pull/836
=> RPC Method Logging

client-c/main.cpp
Sister PR: https://github.com/kframework/evm-semantics/pull/841
=> --timeFreeze parameter for web3 tests

client-c/main.cpp
Sister PR: https://github.com/kframework/evm-semantics/pull/853
=> Add --allowUnlimitedContractSize parameter

plugin-c/json.cpp
Fixes: https://github.com/runtimeverification/firefly/issues/1144
`plugin-c/json.cpp` has an `FDStream` utility class that supports an interface for rapidjson's Reader and Writer classes. It provides functions like Peek, Take, and Put, each of which deal with one character at a time. The current implementation is using system level reads and writes of single characters which doesn't perform very well.
This PR adds a reading ring buffer and a writing buffer to the class which reduces the number of read and write calls made.
=> Buffering for FDStream

plugin-c/crypto.cpp
Fixes runtimeverification/iog-pm#49
=> use koreAllocInteger instead of malloc
