runtimeverification/blockchain-k-plugin

vm/ieleClientUtils.ml, vm/ieleVmTest.ml
add a new module, IeleClientUtils, containing the common parts between the IELE test harness and the solidity-to-IELE test harness. Actual solidity-to-iele test harness will come in a future PR, once it has been more thoroughly tested. We also change the code pertaining to the secretKey field to use from, per the changes in runtimeverification/iele-semantics#90
=> refactor out common code in iele test client

vm/ieleApi.ml, vm/ieleApi.mli, vm/ieleApiClient.ml, vm/ieleClientUtils.ml, vm/ieleVmTest.ml
IOHK folks are still working on getting the Mantis solidity tests running and even when they do, there might be bugs in the IELE/Mantis integration that need to be sorted out before we can run the solidity end to end tests with Mantis, so in the meantime, I created a simple client that communicates with a IELE VM and approximates the same API (modulo the functionality that is used by solidity). This has been tested with an upcoming PR of solidity and it at the very least passes the smoke test.
=> add API client in order to support Solidity-to-IELE harness

vm/ieleApi.ml, vm/ieleClientUtils.ml
Basically previously to_hex was trying to perform some adaptations specific to integers, but this wasn't actually what was needed in the call sites in ieleApi.ml, which just needed to interpret the byte strings as raw bytes. So here we configure those call sites to generate raw hex strings.
=> update to_hex calls in ieleApi.ml to not try to interpret signedness

vm/ieleClientUtils.ml
Addresses need to be exactly 20 bytes long, so we need to call to_hex_unsigned instead of to_hex.
=> more cases of to_hex_unsigned needed

vm/VM.ml
I don't really need all three of you to review this, but if one of you could take a look, that would be great. This is the companion of an upcoming PR to iele-semantics which inserts the Bytes type into the logEntry production.
=> WordStack => Bytes

plugin-c/crypto.cpp
Wait for PR into KEVM which uses this to pass before merging.
=> plugin-c/crypto.cpp: adjust includes to work on Arch

vm-c/kevm/semantics.cpp, vm/VM.ml
Rename the `eip150` and `eip158` schedules according to [#362](https://github.com/kframework/evm-semantics/pull/362)
=> Rename eip150 and eip158 schedules

client-c/json.cpp
This is needed to correctly report json parse errors to the user.
=> detect parse error

vm-c/init.cpp, vm-c/init.h
This should fix a bug during linking on Mac OS and also update us to the latest version of the llvm backend.
=> use setter for thread local variable

client-c/HttpHandler.cpp, client-c/HttpHandler.h
This is required for the test files which contain a list of JSON objects.
=> HttpHandler: Count both square brackets and braces in doneReading

Jenkinsfile, client-c/HttpHandler.cpp, client-c/HttpHandler.h, client-c/main.cpp
Changes:
- The response should contain the same number of `jsonrpc` messages as the request.
- The rpc message is now sent to the `kevm` from the `onEOM()` handle, which is triggered once the entire body of the http request is received.
=> Close HTTPServer

client-c/main.cpp
We were unconditionally outputting a "Socket connection failed ..." message on close of the server. This makes it so the happy path (no crash of server) doesn't take any additional time, but we also skip outputting that message accidentally.
KEVM PR: https://github.com/kframework/evm-semantics/pull/619
=> Quieter Web3 server on successful connections

client-c/main.cpp
https://github.com/runtimeverification/firefly/issues/471
When the K server was getting stuck or crashing, the socket wasn't being closed, making the http server get blocked on a recv call.
=> Shut down the K socket in runKServer

Jenkinsfile, Makefile
Now that we use the K dockerfile, we can simplify our build by removing the LLVM backend checkout.
=> remove llvm backend checkout from build process

client-c/main.cpp
When the web3 semantics get stuck, the entire client is supposed to shutdown. This wasn't happening because the pipe that the K Server communicates to the http server with wasn't being closed properly, so the http server was hanging in a blocking `read` call. This PR fixes that issue.
This PR also updates the `cpp-httplib` submodule to the latest master.
Sister PR: https://github.com/kframework/evm-semantics/pull/878
=> Web3: Close the write end of the K Server's pipe

.gitmodules, Dockerfile, Jenkinsfile, Makefile, plugin-c/crypto.cpp, plugin-c/hash_ext.cpp, plugin-c/plugin_util.cpp, plugin-c/plugin_util.h
First phase of the plugin update.
=> Add Michelson hooks

Makefile, plugin-c/crypto.cpp, plugin/krypto.md
This hook is needed for the TEAL/Clarity semantics.
The hook has been tested against a known input and output pair and passed.
I also fixed a bug in our make clean command which makes it succeed even if our submodules haven't been initialized.
=> Add sha512_256 hook

plugin-c/crypto.cpp
Fix for
```
warning: catching polymorphic type ‘class std::out_of_range’ by value [-Wcatch-value=]
```
=> Add `const&` when catching `std::invalid_argument`

plugin-c/plugin_util.cpp
This resolves compilation issues on recent macOS versions because `sprintf` is deprecated.
=> Replace `sprintf` with `snprintf`

Makefile
I think this should pass `-fPIC` through to the libff build steps; a cursory search suggests that the other libraries already set the flag internally which might suggest why they don't exhibit the same issue.
=> Add `-fPIC` to compiler flags for libff

Makefile
We were not building a position-independent version of libsecp256k1 in the static -> shared workflow used by the new plugin build. This PR fixes that issue and allows me to build KEVM shared libraries locally.
=> Build PIC secp

Makefile
I made an error when I created the build system for the avx2 blake2 code: I disabled compiling the blake2 code with optimizations. This made it slower rather than faster.
This PR ought to fix the issue.
=> fix bug in automatic rules for making blake2

.gitmodules, Makefile, flake.nix, tests/krypto-hooks/kryptotest.mak
* Removes submodule `secp256k1` (but checkouts of earlier versions will still include it)
* moves `blake2.a` artefact to `build/blake2/lib` directory to align with conventions for `libff` and `libcryptopp` (`make clean` will now remove this file, too)
* calls `make blake2` in `flake.nix` build phase to build/provide `blake2.a` to clients.
These changes make using the plugin in downstream dependencies under `nix` a bit easier.
The dependent still needs to build the code from source (the `*.o` files are not provided) but does not have to replicate the build logic for the `blake2`  parts.
=> Adapt recent refactorings for better downstream usage

krypto/src/tests/integration/test-data/ecdsa-test.k, plugin/krypto.md
This PR is a simple mechanical change to remove the `klabel, symbol` attribute pair in anticipation of `klabel` finally being deprecated; usages are replaced with 1-argument `symbol(_)`.
=> Deprecate `klabel` attribute

Makefile
Should fix #152 
#173 made a change to how cryptopp is built which dropped the `-fPIC` flag, causing the plugin-c library that gets built to be unusable. This fixes that.
=> Compile the cryptopp lib with -fPIC

krypto/src/tests/integration/test_hooks.py, plugin-c/kzg.cpp
This PR is a small bug fix for the PR [here](https://github.com/runtimeverification/blockchain-k-plugin/pull/209), adding a hook for `verify_kzg_proof`.
We add a regression test that calls the hook twice in a single program. This would be likely to trigger the bug (although the behavior was non deterministic)
=> Bug fix for EIP-4844 verify_kzg_hook

Makefile
Follow up to https://github.com/runtimeverification/blockchain-k-plugin/pull/211, https://github.com/runtimeverification/blockchain-k-plugin/pull/210.
This PR adds another small fix for the PR https://github.com/runtimeverification/blockchain-k-plugin/pull/209, adding a hook for `verify_kzg_proof`. 
This line https://github.com/runtimeverification/blockchain-k-plugin/blob/e0b9fcf17c837859a2eb101f53710ab5d5cb8b0c/create_trusted_setup_str.sh#L6
causes the following error when I'm trying to build the plugin on a macOS:
```sh
INFO 2025-03-06 23:22:26,347 pyk.utils - [PID=52737][stde] /private/var/folders/nm/0h7qd27j4c53c5k6crqzz16c0000gn/T/kdist-evm-semantics-plugin-_hjgx1og/build/c-kzg-4844/trusted_setup.cpp:1:34: warning: missing terminating '"' character [-Winvalid-pp-token]
INFO …
```
=> Fix macOS syntax error in kzg-4844 script

Makefile, krypto/src/tests/integration/test_hooks.py, plugin-c/crypto.cpp, plugin/krypto.md
Here is the (Pi2) EVM PR that uses this:
https://github.com/Pi-Squared-Inc/evm-semantics/pull/42
=> Add hooks for BLS12-381

krypto/src/tests/integration/test_hooks.py, plugin-c/crypto.cpp, plugin/krypto.md
https://github.com/Pi-Squared-Inc/evm-semantics/pull/42 has a corresponding commit that uses the new hooks.
The EVM semantics implementation used a naive and slow hand-built implementation for multi-scalar multiplication (i.e., computing `s1*p1+s2*p2+...+sn*pn`). There are two reasons for the new hooks:
1. We should not use hand-built algorithms for cryptographic stuff, even trivial ones like the EVM semantics used.
2. The Ethereum gas costs make sense only when using an efficient algorithm.
=> Add hooks for multi-scalar-multiplication
